// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ahmedsameha1/todo_backend_go_to_practice/common (interfaces: DBRows)

// Package common is a generated GoMock package.
package common

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockDBRows is a mock of DBRows interface.
type MockDBRows struct {
	ctrl     *gomock.Controller
	recorder *MockDBRowsMockRecorder
}

// MockDBRowsMockRecorder is the mock recorder for MockDBRows.
type MockDBRowsMockRecorder struct {
	mock *MockDBRows
}

// NewMockDBRows creates a new mock instance.
func NewMockDBRows(ctrl *gomock.Controller) *MockDBRows {
	mock := &MockDBRows{ctrl: ctrl}
	mock.recorder = &MockDBRowsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDBRows) EXPECT() *MockDBRowsMockRecorder {
	return m.recorder
}

// Err mocks base method.
func (m *MockDBRows) Err() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Err")
	ret0, _ := ret[0].(error)
	return ret0
}

// Err indicates an expected call of Err.
func (mr *MockDBRowsMockRecorder) Err() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Err", reflect.TypeOf((*MockDBRows)(nil).Err))
}

// Next mocks base method.
func (m *MockDBRows) Next() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Next")
	ret0, _ := ret[0].(bool)
	return ret0
}

// Next indicates an expected call of Next.
func (mr *MockDBRowsMockRecorder) Next() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Next", reflect.TypeOf((*MockDBRows)(nil).Next))
}

// Scan mocks base method.
func (m *MockDBRows) Scan(arg0 ...interface{}) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{}
	for _, a := range arg0 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Scan", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Scan indicates an expected call of Scan.
func (mr *MockDBRowsMockRecorder) Scan(arg0 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Scan", reflect.TypeOf((*MockDBRows)(nil).Scan), arg0...)
}
